[book]
title = "mdBook + GitHub Pages Test"
author = ["Your Name"]

[build]
create-missing = true

[preprocessor]

[preprocessor.wavedrom]
command = "mdbook-wavedrom"

[output]

[output.html]
additional-js = ["wavedrom.min.js", "wavedrome-default.js"]
